name: Decommission repository

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to decommission (matches repos/<repo>.yaml)'
        required: true

jobs:
  decommission:
    uses: G-Research/github-terraformer/.github/workflows/decommission.yaml@main
    with:
      repo: ${{ github.event.inputs.repo }}
      gcss_ref: main
      tfc_org: "GR-OSS"
    secrets:
      tfc_token: ${{ secrets.TFC_TOKEN }}
