name: Import organisation

on:
  workflow_dispatch:

jobs:
  import-org:
    uses: G-Research/github-terraformer/.github/workflows/import-org.yaml@main
    with:
      gcss_ref: main
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
