name: Unnamed

on:
  workflow_run:
    workflows: [ "Terraform Plan" ]
    types:
      - requested

jobs:
#  bootstrap:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
  terraform-plan:
    uses: G-Research/github-terraformer/.github/workflows/tf-plan.yaml@improvements
    with:
      commit_sha: ${{ github.event.workflow_run.head_sha }}
      gcss_ref: improvements
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      tfc_token: ${{ secrets.TFC_TOKEN }}