name: WIP

on:
  workflow_dispatch:

jobs:
  wip:
    runs-on: ubuntu-latest
    name: WIP
    steps:
      - name: Checkout repositories configuration
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo ${GITHUB_WORKSPACE}
          ls -la

#      - name: Assemble GCSS
#        uses: ./.github/actions/assemble-gcss